[workspace]
members = ["crate_*"]
default-members = ["crate_mod_shuffle"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"
dead_code = "allow"

[workspace.dependencies]
derive_more = "0.99"
include_dir = "0.7.3"
