[package]
name = "cli_mod_shuffle"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
derive_more.workspace = true
include_dir.workspace = true

clap = { version = "4.5.4", features = [
    "env",
    "derive",
    "string",
    "wrap_help",
] }
dialoguer = "0.11.0"
