[package]
name = "egui_mod_shuffle"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
egui_extras = "0.27"
egui_inbox = "0.4"

derive_more.workspace = true
include_dir.workspace = true
